default:
    image: OpenJDK-15.0.2

setup-job:
    stage: setup
    script:
        - echo "JAVA_HOME=${JAVA_HOME}"
build-job:
    stage: build
    script:
        - ./gradlew assemble
        - echo "Assemble .."
deploy-job:
    stage: deploy
    script:
        - echo "Deploy"
        - ./gradlew test
